### ISSUE TITLE
How to install after building with cmake manually?

### ISSUE THREAD

**Issue by shaljam** [src-d/minhashcuda#10]
I built with `cmake`. I wonder how can I install it to python packages?

**Comment by vmarkovtsev** [comment]
Hi! Have you tried

```
pip3 install .
```

**Comment by shaljam** [comment]
Hi, I just tried and got the following:
```
pip install .
Processing /home/ali/thesis/minhashcuda
Requirement already satisfied: numpy in /home/ali/.pyenv/versions/3.6.5/envs/event_detection/lib/python3.6/site-packages (from libMHCUDA==2.0.5) (1.14.3)
Installing collected packages: libMHCUDA
  Running setup.py install for libMHCUDA ... error
    Complete output from command /home/ali/.pyenv/versions/3.6.5/envs/event_detection/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-6yiqz232/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0pagm3lj/install-record.txt --single-version-externally-managed --compile --install-headers /home/ali/.pyenv/versions/3.6.5/envs/event_detection/include/site/python3.6/libMHCUDA:
    running install
    running build
    running build_py
    CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-6yiqz232/CMakeCache.txt is different than the directory /home/ali/thesis/minhashcuda where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6yiqz232/setup.py", line 90, in <module>
        "Programming Language :: Python :: 3.6"
      File "/home/ali/.pyenv/versions/3.6.5/envs/event_detection/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ali/.pyenv/versions/3.6.5/envs/event_detection/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-6yiqz232/setup.py", line 34, in run
        self._build()
      File "/tmp/pip-req-build-6yiqz232/setup.py", line 52, in _build
        "."))
      File "/home/ali/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCUDA_TOOLKIT_ROOT_DIR=must_export_CUDA_TOOLKIT_ROOT_DIR', '-DPYTHON_DEFAULT_EXECUTABLE=python3', '-DPYTHON_INCLUDE_DIRS=/home/ali/.pyenv/versions/3.6.5/include/python3.6m', '-DPYTHON_EXECUTABLE=/home/ali/.pyenv/versions/3.6.5/envs/event_detection/bin/python', '-DPYTHON_LIBRARY=/home/ali/.pyenv/versions/3.6.5/lib/libpython3.6m.a', '.')' returned non-zero exit status 1.
```

I built with the following:
```
rm -rf CMakeCache.txt CMakeFiles Makefile cmake_install.cmake libMHCUDA.egg-info
cmake -D NUMPY_INCLUDES=/home/ali/.pyenv/versions/event_detection/lib/python3.6/site-packages/numpy/core/include/ -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -D CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so -DCMAKE_BUILD_TYPE=Release .
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/gcc-7
-- Check for working C compiler: /usr/bin/gcc-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PythonLibs: /usr/lib/libpython3.6m.so (found suitable version "3.6.5", minimum required is "3")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ali/thesis/minhashcuda
```
```
make
[ 25%] Building NVCC (Device) object CMakeFiles/MHCUDA.dir/MHCUDA_generated_kernel.cu.o
ptxas info    : 0 bytes gmem, 4 bytes cmem[3]
ptxas info    : Compiling entry function '_Z21weighted_minhash_cudaPKfS0_S0_S0_PKjS2_PKiijjPj' for 'sm_61'
ptxas info    : Function properties for _Z21weighted_minhash_cudaPKfS0_S0_S0_PKjS2_PKiijjPj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 34 registers, 400 bytes cmem[0], 56 bytes cmem[2]
ptxas info    : Compiling entry function '_Z8log_cudajPf' for 'sm_61'
ptxas info    : Function properties for _Z8log_cudajPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 8 registers, 336 bytes cmem[0], 44 bytes cmem[2]
ptxas info    : Compiling entry function '_Z10gamma_cudajPKfPf' for 'sm_61'
ptxas info    : Function properties for _Z10gamma_cudajPKfPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 9 registers, 344 bytes cmem[0], 44 bytes cmem[2]
Scanning dependencies of target MHCUDA
[ 50%] Building CXX object CMakeFiles/MHCUDA.dir/minhashcuda.cc.o
[ 75%] Building CXX object CMakeFiles/MHCUDA.dir/python.cc.o
[100%] Linking CXX shared library libMHCUDA.so
[100%] Built target MHCUDA
```

**Comment by vmarkovtsev** [comment]
Hi, run `git clean -xfd`

**Comment by shaljam** [comment]
@vmarkovtsev 
I get the same error.
When I try to build with `pip` or `setup.py`, I get an error regarding `numpy` includes:

```
CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so pip install .
...
/tmp/pip-req-build-_esrwbrt/python.cc:5:10: fatal error: numpy/arrayobject.h: No such file or directory
     #include <numpy/arrayobject.h>
...
```

**Comment by shaljam** [comment]
And adding `NUMPY_INCLUDES=/home/ali/.pyenv/versions/event_detection/lib/python3.6/site-packages/numpy/core/include/` which helps when using `cmake`, doesn't help here.

**Comment by vmarkovtsev** [comment]
Right, you are building inside `pipenv` and it prevents `cmake` from detecting all the needed libraries and headers. I suggest you use Docker instead.

You can also add the numpy def at https://github.com/src-d/minhashcuda/blob/master/setup.py#L51

That being said, this project officially does not support building in `pipenv`, `conda` or any other virtual Python environment created by the evil genious :)

**Comment by shaljam** [comment]
Getting around `numpy` error I get:
```
...
    [ 50%] Building CXX object CMakeFiles/MHCUDA.dir/minhashcuda.cc.o
    [ 75%] Building CXX object CMakeFiles/MHCUDA.dir/python.cc.o
    [100%] Linking CXX shared library libMHCUDA.so
    /usr/bin/ld: /home/ali/.pyenv/versions/3.6.5/lib/libpython3.6m.a(compile.o): relocation R_X86_64_PC32 against symbol `PyExc_SyntaxError' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
...
```

**Comment by vmarkovtsev** [comment]
Closing this since building in virtual environments is not supported. I will add it to the README. Feel free to PR any fixes which you find to help with `pyenv` though.

**Comment by shaljam** [comment]
If someone gets here, to solve `relocation R_X86_64_PC32 against symbol 'PyExc_SyntaxError' can not be used when making a shared object; recompile with -fPIC` , you have to use `PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.5`.
